# Generated by Django 6.0.3 on 2026-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_topic_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select up to 4 JAMB subjects', related_name='profiles', to='questions.subject'),
        ),
    ]
